#!/bin/sh

export IPADDR="192.168.1.103"
export NETMASK="255.255.255.0"
export BROADCAST="192.168.1.255"
export GATEWAY="192.168.1.254"

if [ ! -x /sbin/ifconfig ]
then
    exit 0
fi

if [ "$1" = "stop" -o "$1" = "restart" ]
then
    echo "Closeing the eth0: "
    ifconfig eth0 down
fi

if [ "$1" = "start" -o "$1" = "restart" ]
then
    echo "Setting up networking on loopback device: "
    ifconfig lo 127.0.0.1
    route add -net 127.0.0.0 netmask 255.0.0.0 lo

    ifconfig eth0 $IPADDR
  
    mount -n -o nolock 192.168.1.101:/home/nop/DownLoadFiles /mnt/
fi
